name: azlyrics
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  html: ^0.15.0
  http: ^0.13.3
  sprintf: ^6.0.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
